import Context from "../context/CalendarContext";

import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Calendar from '../components/calendar/Calendar'

const Home: NextPage = () => {
  return (
    <Context>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>


        <main className={styles.main}>
          <Calendar />
        </main>
      </div>
    </Context>
  )
}

export default Home
